.to-gcs:
  stage: Publish
  image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
  variables:
    EDITION: "ce"
    BUCKET: "download.passbolt.com"
    PREFIX: "installer"
  script:
    - gcloud auth activate-service-account --key-file "$SVC_ACC"
    - gsutil cp "passbolt-repo-setup.$EDITION.sh" "gs://$BUCKET/$EDITION/$PREFIX/"
  after_script:
    gsutil -m setmeta -r -h "Content-Type:text/html" \
      -h "Cache-Control:no-cache" \
      "gs://$BUCKET/$PREFIX/*"
  rules:
    - if: '$CI_COMMIT_TAG != null'

ce:
  extends: .to-gcs

pro:
  extends: .to-gcs
  variables:
    EDITION: "pro"
