Repository filesystem scan:
  stage: Quality
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/aquasec/trivy:latest
  script:
    - trivy fs .

Configuration scan:
  stage: Quality
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/aquasec/trivy:latest
  script:
    - trivy config .