.shellcheck:
  stage: Quality
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine:3.16
  variables:
    SCRIPTFILE: ""
  script:
    - apk add --no-cache shellcheck
    - shellcheck ${SCRIPTFILE}

ShellCheck CE:
  extends: .shellcheck
  variables:
    SCRIPTFILE: "passbolt-repo-setup.ce.sh"

ShellCheck PRO:
  extends: .shellcheck
  variables:
    SCRIPTFILE: "passbolt-repo-setup.pro.sh"